### PR TITLE
StackOverflowError in VarMap.map when calling getParameterTypes()

### LINKED ISSUE #27: StackOverflowError in VarMap.map when calling GenericTypeReflector.getParameterTypes()
mfriedenhagen reported an issue in Spock https://github.com/spockframework/spock/issues/1909 where geantyref throws a `StackOverflowError`.

I have removed the Spock dependency from the reproducer attached to the Spock issue, and the error is still there:

```java

import java.lang.reflect.Method;
import java.util.Objects;

public class StackOverflowReproducer {

  static abstract class Status<StatusT, StatusBuilderT> {
    static class Builder<StatusT, StatusBuilderT> {
    }
  }

  static abstract class Resource<StatusT, StatusBuilderT> {
  }

  static class ProjectValidator {
    public <
      StatusT extends Status<StatusT, StatusBuilderT>,
      StatusBuilderT extends Status.Builder<StatusT, StatusBuilderT>,
      T extends Resource<StatusT, StatusBuilderT>>
    void validate(long id, Class<T> klass) {
      throw new UnsupportedOperationException("Just for testing");
    }
  }

  public static void main(String[] args) throws NoSuchMethodException {
    Class<?> cls = ProjectValidator.class;
    Method method = Objects.requireNonNull(cls.getMethod("validate", long.class, Class.class));
    io.leangen.geantyref.GenericTypeReflector.getParameterTypes(method, cls);
  }
}
```

The exception stack looks like:

```
java.lang.StackOverflowError
	at java.base/sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:144)
	at java.base/sun.reflect.generics.reflectiveObjects.TypeVariableImpl.typeVarIndex(TypeVariableImpl.java:227)
	at java.base/sun.reflect.generics.reflectiveObjects.TypeVariableImpl.getAnnotatedBounds(TypeVariableImpl.java:220)
	at java.base/sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeVariableImpl.getAnnotatedBounds(AnnotatedTypeFactory.java:383)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
	at io.leangen.geantyref.VarMap.map(VarMap.java:115)
	at io.leangen.geantyref.VarMap.map(VarMap.java:148)
	at io.leangen.geantyref.VarMap.map(VarMap.java:98)
```

The used geantyref version is `io.leangen.geantyref:geantyref:1.3.15`
Tested for Java `8` and `17`

### PR DESCRIPTION
**Pull request by AndreasTu**
The VarMap now tracks the currently resolving TypeVars to detect, if we already resolve the same TypeVar.

Fixes #27

### CODE REVIEW

**Comment by leonard84** [comment]
@kaqqao, sorry to ping you. We'd need this fix to resolve https://github.com/spockframework/spock/issues/1909, do you think you could merge this and release a new version soon?

**Comment by kaqqao** [comment]
Oh hey!
Sorry for the radio silence. I wasn't very active in the past months. Sure, I'll try to have this merged/released today.

**Comment by AndreasTu** [comment]
That would be great. Thank you very much!

File: src/main/java/io/leangen/geantyref/VarMap.java [hunk 1]
```diff
@@ -95,7 +102,18 @@ AnnotatedType map(AnnotatedType type, MappingMode mappingMode) {
             if (!map.containsKey(tv)) {
                 if (mappingMode.equals(MappingMode.ALLOW_INCOMPLETE)) {
                     AnnotatedTypeVariable variable = (AnnotatedTypeVariable) type;
-                    AnnotatedType[] bounds = map(variable.getAnnotatedBounds(), mappingMode);
+                    AnnotatedType[] bounds;
+                    if(!currentlyResolvingTypeVariable.add(tv)) {
+                        //Issue #27: We have already seen this TypeVariable during the current resolution, so we need to abort
+                        //Otherwise, we get a StackOverflowError
+                        bounds = new AnnotatedType[]{new AnnotatedTypeImpl(Object.class)};
```
Comment (kaqqao) [inline src/main/java/io/leangen/geantyref/VarMap.java:109]: Shouldn't it be just `return type` at this point? If I'm getting this right, at this point we know the variable isn't resolvable, so we can leave it as-is, right? That way the resulting type remains recursive, which I think is correct here.
What do you think?

File: src/main/java/io/leangen/geantyref/VarMap.java [hunk 2]
```diff
@@ -95,7 +102,18 @@ AnnotatedType map(AnnotatedType type, MappingMode mappingMode) {
...
+                    }else {
+                        try{
+                            bounds = map(variable.getAnnotatedBounds(), mappingMode);
+                        }finally{
+                            currentlyResolvingTypeVariable.remove(tv);
+                        }
```
Comment (kaqqao) [inline src/main/java/io/leangen/geantyref/VarMap.java:115]: Not sure I get the point behind the `try` block?

Comment (AndreasTu) [reply src/main/java/io/leangen/geantyref/VarMap.java:115]: To cleanup the set, if a var is used in multiple places during parameter resolution, otherwise a second use to the var, would terminate too early.

File: src/main/java/io/leangen/geantyref/VarMap.java (hunk 1 above)
Comment (kaqqao) [reply src/main/java/io/leangen/geantyref/VarMap.java:109]: Hmm, some annotation merging maybe has to happen first 🤔 I have to think/tinker with it a little more.

Comment (AndreasTu) [reply src/main/java/io/leangen/geantyref/VarMap.java:109]: I though, I just break the recursion here with Object, which is IMHO the "best" guess, if we have a cycle, and let the other code merge the annotations etc. as it would normally.
